### ISSUE TITLE
Some questions about parameter setting

### ISSUE THREAD

**Issue by TqXue** [bupt-ai-cz/HSA-NRL#4]
1、Why the value of noise_rate is 0.15 in line 66 step1.py?
2、Also in step1.py, why the filter_ratio is the product of noise_rate and 1.5 in line 216, why 1.5?
3、Why you set the value of forget_rate 0.01 when running NSHE.py?
Sorry to disturb you again

**Comment by buptcwk** [comment]
1. This is the estimated noise ratio for Chaoyang dataset.
2. This is our hyper-parameter setting scheme, we mentioned in our paper (Subsection "Implementation and Parameter Settings" in Section "Experiment").
3. We set the value of forget_rate 0.01 since the noise ratio of the generated "Almost clean data" is quite low, as mentioned in our paper (Table VIII). For datasets with a high noise ratio, you can also increase this number.

**Comment by TqXue** [comment]
Oh, thanks a lot! Maybe I should read your paper carefully again!
